### ISSUE TITLE
Line ending style with readme.txt

### ISSUE THREAD

**Issue by WynnChen** [OmegaT-L10N/zh_CN#3]
I noticed that readme.txt (EN) in source folder uses Windows style line endings("\r\n"), But the generated target file readme_zh_CN.txt by OmegaT uses Unix-style line endings ("\n").
This makes we can't view zh_CN readme file properly after OmegaT installtion, since it is opened by notepad.
I did some research but didn't find out how to make the line ending style be the same with source file. So is there a way to solve this issue?

@kosivantsov

**Comment by amake** [comment]
This will be addressed in the next release of OmegaT. No action is needed.

# Details

The files in question are stored in SVN with "native" EOL chars. This means you will get LF if checking out on Linux or Mac, or CRLF on Windows. 

Previously, official Windows builds were made on Windows, so the files were CRLF. In 4.2.0 we began building everything on Linux, so the files became LF.

Now we have enforced in the build system that the files in question will be converted to CRLF in all cases. This is because Windows is deficient in only being able to display CRLF correctly out of the box, while all other platforms have default text editors that can handle either.

**Comment by WynnChen** [comment]
Thanks for the answer!

**Comment by CPCer** [comment]
@WynnChen Hi i wonder if you're currently working on the localisation of OmegaT website and docs. I'm willing to do some help.

**Comment by WynnChen** [comment]
@CPCer Welcome, feel free to join!

**Comment by CPCer** [comment]
thx just wondering what to do 🙌
